### ISSUE TITLE
premium content

### ISSUE THREAD

**Issue by tirzah2** [coffiarts/FoundryVTT-crunch-my-party#1] opened 2023-07-16 23:30 UTC
hi, for some  reason it appears as premium content on foundry hub.

**Comment by coffiarts** [comment] 2023-07-17 06:44
Thanks for bringing this to my attention!
Maybe this is important, as I am unfamiliar with Foundry Hub (and its connection to Forge VTT), so I may have overlooked something which is causing confusion.
To state it right ahead: It is _NOT_ my intention that anybody be _forced_ to pay for my mod. _It is and will remain available for free!_

I guess this the new "Buy on the Bazaar for $1.99" button here on the hub is causing the issue? https://www.foundryvtt-hub.com/package/crunch-my-party/

If so, could you please check:

- Can you still uninstall and reinstall my mod through _Foundry's own setup menu_? Because this _MUST_ still work without any "premium" oder "buying" nuisance
- Alternatively, simply follow that "Buy..." button (it leads to the mod's download page at Forge VTT), and then choose the "Pay what you like" option. Yes, it _MUST_ still be possible to download & install without paying anything, because otherwise, I would have completey misunderstood something in this process.

**Some background:**
A couple of days ago, I followed the recommendation of another modder to publish my mods on The Forge. The aim is only to provide an _OPTION_ for downloaders to "donate" something (based on the "pay what you like" option"). But it's really meant as abolutely optional. I've alsa added a related section to my Readme stating this.
However, Forge allows to add a "price" (which in this case is meant as a "recommended" price, so _still_ optional). I suppose this causes that "Buy ... $1.99" button, which now may be very confusing to people!
To be safe, I'll also check if I can change that "price" down to 0.00, to limit the possible confusion.

**Comment by coffiarts** [comment] 2023-07-18 11:35
@tirzah2 - Any chance for a feedback on this? Based on what I posted above, I'd like to consider this isse "as designed", although I understand the confusion it may cause.
I'd love to hear if my post above clarifies ist or if you see need for further action.
I wouldn't like the new "premium" flag on Forge to keep players from downloading my mod.

**Comment by coffiarts** [comment] 2023-07-20 12:33
Closing this as NOT being a bug. The "premium" flag on The Forge doesn't imply that you have to pay anything. Everybode can still download and install my mod for for free, as described above. Voluntary payment via The Forge ("pay what you like") is only an option, the given price only a suggestion.

**Closed by coffiarts** 2023-07-20 12:33 UTC
